// <auto-generated/>
using Kubernox.Client.Api.Identity.Login;
using Kubernox.Client.Api.Identity.Profile;
using Kubernox.Client.Api.Identity.Refresh;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubernox.Client.Api.Identity
{
    /// <summary>
    /// Builds and executes requests for operations under \api\identity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class IdentityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The login property</summary>
        public global::Kubernox.Client.Api.Identity.Login.LoginRequestBuilder Login
        {
            get => new global::Kubernox.Client.Api.Identity.Login.LoginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The profile property</summary>
        public global::Kubernox.Client.Api.Identity.Profile.ProfileRequestBuilder Profile
        {
            get => new global::Kubernox.Client.Api.Identity.Profile.ProfileRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The refresh property</summary>
        public global::Kubernox.Client.Api.Identity.Refresh.RefreshRequestBuilder Refresh
        {
            get => new global::Kubernox.Client.Api.Identity.Refresh.RefreshRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubernox.Client.Api.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/identity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubernox.Client.Api.Identity.IdentityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public IdentityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/identity", rawUrl)
        {
        }
    }
}
