// <auto-generated/>
using Kubernox.Client.Api.Identity;
using Kubernox.Client.Api.SshKeys;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Kubernox.Client.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The identity property</summary>
        public global::Kubernox.Client.Api.Identity.IdentityRequestBuilder Identity
        {
            get => new global::Kubernox.Client.Api.Identity.IdentityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sshKeys property</summary>
        public global::Kubernox.Client.Api.SshKeys.SshKeysRequestBuilder SshKeys
        {
            get => new global::Kubernox.Client.Api.SshKeys.SshKeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubernox.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Kubernox.Client.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
